# Change this value to your own domain.
base_url = "zackerthescar.github.io

title = ""
description = ""

# minify_html = true
compile_sass = true

[extra]
author = "ACM UMN"
menu = [
    { url = "/personal-site/", name = "Home" },
]
