# Change this value to your own domain"
base_url = "https://zackerthescar.github.io/personal-site/"

title = ""
description = ""

# minify_html = true
compile_sass = true

[extra]
author = "ACM UMN"
menu = [
    { url = "", name = "Home" },
    { url = "https://www.youtube.com/watch?v=dQw4w9WgXcQ", name = "click this"}
]
